// Generated by https://quicktype.io

export interface ResDataBooking {
  trip_date: TripDate;
  code: string;
  individuals: IndividualElement[];
  status: string;
  id: number;
}

export interface IndividualElement {
  individual_type: IndividualType;
  quantity: number;
}
enum IndividualType {
  FOREIGN = 'Extranjeros',
  ELDERLY = 'Adultos Mayores',
  ADULT = 'Adultos',
  TEENAGER = 'Adolescentes',
  CHILDREN = 'Niños',
  BABIES = 'Bebés',
}

export interface IndividualIndividual {
  id: number;
  individual_type: IndividualType;
  min_age: number;
  max_reservation_quantity: number;
}

export interface TripDate {
  trip: Trip;
  date_type: string;
  start_date: string;
  end_date: string;
  total_places: number;
  month: string;
}

export interface Trip {
  product: Product;
  trip_id: number;
  trip_name: string;
  days: number;
  nights: number;
  price: string;
  wetravel_uuid: null;
  has_booking: boolean;
}

export interface Product {
  id: number;
  product_type: ProductType;
  code: string;
  label: string;
  name: string;
  location: string;
  physical_performance: number;
  acommodation_quality: number;
  tags: Tag[];
  image_url: string;
}

export interface ProductType {
  id: number;
  name: string;
  label: string;
}

export interface Tag {
  id: number;
  name: string;
  label: string;
  active: boolean;
  image_url: string;
}
